### ISSUE TITLE
Password Change logout handling

### ISSUE THREAD

**Issue by Thiritin** [Thiritin/identity#10]
Currently, to destroy session button will log you out of your current device. It should log you out of all devices instead.

**Comment by mowny** [comment]
Session handling is a bit weird anyway. After the session times out, a reload redirects to https://identity.eurofurence.org/auth/choose. Clicking "Login with existing account" gets me directly to the dashboard without having to actually log in.

**Comment by Thiritin** [comment]
Hey @mowny 

Thanks for your comment. Yes that is wanted as the openid connect Server saves a cookie depending on if you habe set the remember me.

The clients all got a limited session time. Although that session time does not end the cookie session at the idp.

E.x. the idp may have a cookie lifetime of 180 days meanwhile the apps only got an hour. 

The right solution should be to redirect when the session times out.

**Comment by Thiritin** [comment]
Fixed by implementing #11, sessions are not concern of the idp. So session management can only be done by the idp for the IDP Apps not for the Reg as example. A fix for this could be backchannel logout.
