### ISSUE TITLE
artist credit for splash page image

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [Thiritin/identity#35]
Using the image for Eurofurence related media has been cleared, we should just give credit in some way.

The artist is:

~~Caraid~~
~~https://twitter.com/CaraidArt~~

**Comment by Thiritin** [comment]
@Jumpy-Squirrel as we noted the current image is proparby made by someone else. Can you get the new credits to me?
![image](https://user-images.githubusercontent.com/6755282/218284983-e8461660-ede6-4e05-bc59-9de29462fb6a.png)

**Comment by Jumpy-Squirrel** [comment]
That'd be https://twitter.com/ArtYeen
