### ISSUE TITLE
is it intentional that the user name (aka Nickname) field cannot be changed?

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [Thiritin/identity#49]
The Username field seems disabled by default which makes it likely we want to prevent editing. 

If intentional, needs server side validation: Simply changing the HTML in the browser will still allow changing it at the moment :)

If unintentional, allow editing in UI too.

**Comment by Thiritin** [comment]
This is planned to be implemented, but hasn't been set yet. Username changes should be somewhat restricted, to

A: usernames cannot be duplicated
B: Possibly, users should not change their usernames twice in a row e.x. you can only change your username every 14 days as example.

**Comment by Jumpy-Squirrel** [comment]
Okay, I guess in this case, we should forbid changes server-side for now.

**Comment by Thiritin** [comment]
curretly changes from the username is not supported. I will add username changes at some point but I do not see this as a priority for now.

**Comment by Thiritin** [comment]
> Okay, I guess in this case, we should forbid changes server-side for now.

This has been actioned, as it was possible if you had done a manual request. Although it would have been validated.
