### ISSUE TITLE
could not confirm email address

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [Thiritin/identity#52]
yesterday I created a new account called regtest4, and around 16:58-17:05 tried multiple times to confirm the email address. It kept bringing me back to the confirm email dialog. 

I had it send me 3 emails and tried their links.

After several failed attempts it suddenly worked, though I have no idea what I did different. Maybe your logs can help you there?

Could you check this part of the system again? It seems there's still some bugs there.

**Comment by Thiritin** [comment]
Could be simply that once you verified your email that the verify page does not redirect to the dashboard automatically. Will add a redirection.
